### ISSUE TITLE
The implementation of the algorithm

### ISSUE THREAD

**Issue by severous** [hamrel-cxu/EnbPI#6]
compute_PIs_Ensemble_online is differrent with Algorithm 1 mentioned in your paper. I cannot understant the following code
```python
else:  # if aggregating an empty set of models, predict zero everywhere
                resid_LOO = np.abs(self.Y_train[i])
                self.Ensemble_online_resid = np.append(self.Ensemble_online_resid, resid_LOO)
                out_sample_predict[i] = np.zeros(n1)
        sorted_out_sample_predict = np.sort(out_sample_predict, axis=0)[ind_q]  # length n1
```
Also, the length of tensor `sorted_out_sample_predict` is not equal to the number of test dataset in your source code. And I cannot understand the value of  `sorted_out_sample_predict` can be zero

**Comment by hamrel-cxu** [comment]
How is "compute_PIs_Ensemble_online" different? Please be more specific.

The else loop you pasted is more like a placeholder. In practice, because the number of bootstrap models to be aggregated follows a binomial distribution, w.h.p. this else loop will not be executed. 

The length of "sorted_out_sample_predict" equals the number of test sample points, which is n1 in the code. Where do you find the lengths to be incompatible?
